version: '2.4'
services:
  nginx:
    image: nginx:1.19.5-alpine
    volumes:
      - ./env/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 81:81
      - 82:82
      - 83:83
    depends_on:
      - frontend-service-php
      - auth-service-php

  frontend-service-php:
    build: ./env/php
    container_name: frontend-service-php
    volumes:
      - './frontend-service:/home/project/src'
      - './shared:/home/project/shared'
    environment:
      ENABLE_PHP_MODULES: 'mysqlnd pdo pdo_mysql pdo_sqlite curl json intl mbstring gd xml zip ctype exif pdo_sqlite ftp tokenizer dom simplexml apcu xmlwriter fileinfo bcmath iconv xdebug posix xmlreader soap imap ssh2 phar'

  auth-service-php:
    build: ./env/php
    container_name: auth-service-php
    volumes:
      - './auth-service:/home/project/src'
      - './shared:/home/project/shared'
    depends_on:
      - auth-service-db
    environment:
      ENABLE_PHP_MODULES: 'mysqlnd pdo pdo_mysql pdo_sqlite curl json intl mbstring gd xml zip ctype exif pdo_sqlite ftp tokenizer dom simplexml apcu xmlwriter fileinfo bcmath iconv xdebug posix xmlreader soap imap ssh2 phar'

  auth-service-db:
    image: mysql:8.0.22
    container_name: auth-service-db
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

  product-service-php:
    build: ./env/php
    container_name: product-service-php
    volumes:
      - './product-service:/home/project/src'
      - './shared:/home/project/shared'
    depends_on:
      - product-service-db
    environment:
      ENABLE_PHP_MODULES: 'mysqlnd pdo pdo_mysql pdo_sqlite curl json intl mbstring gd xml zip ctype exif pdo_sqlite ftp tokenizer dom simplexml apcu xmlwriter fileinfo bcmath iconv xdebug posix xmlreader soap imap ssh2 phar'

  product-service-db:
    image: mysql:8.0.22
    container_name: product-service-db
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

  order-service-php:
    build: ./env/php
    container_name: order-service-php
    volumes:
      - './order-service:/home/project/src'
      - './shared:/home/project/shared'
    depends_on:
      - order-service-db
    environment:
      ENABLE_PHP_MODULES: 'mysqlnd pdo pdo_mysql pdo_sqlite curl json intl mbstring gd xml zip ctype exif pdo_sqlite ftp tokenizer dom simplexml apcu xmlwriter fileinfo bcmath iconv xdebug posix xmlreader soap imap ssh2 phar'

  order-service-db:
    image: mysql:8.0.22
    container_name: order-service-db
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
