services:
    _defaults:
        public: true

    Shared\ApiGeneralBundle\Storage\SecurityContextStorage: ~
    Shared\ApiGeneralBundle\Storage\SecurityContextStorageInterface: '@Shared\ApiGeneralBundle\Storage\SecurityContextStorage'
