services:
    _defaults:
        public: true

    Shared\AuthClientBundle\AuthClient:
        arguments:
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@Shared\ApiClientSecurityBundle\Factory\ClientFactoryInterface'
            - '@Shared\ApiGeneralBundle\Utils\ErrorHandler'
            - '%auth_client.api_base_url%'

    Shared\AuthClientBundle\AuthClientInterface: '@Shared\AuthClientBundle\AuthClient'
