security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: false
            guard:
                authenticators:
                    - Shared\ApiServerSecurityBundle\Security\JwtAuthenticator
